[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/new"
  to = "https://vivi-swart.vercel.app/new"
  status = 200
  force = true

[[redirects]]
  from = "/new/*"
  to = "https://vivi-swart.vercel.app/new/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
